version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - company-service
    networks:
      - backend

  company-service:
    build:
      context: ./company-service
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge